# Generated by Django 4.2.16 on 2024-11-12 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='作者编号')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=50, verbose_name='登录密码')),
                ('realname', models.CharField(blank=True, db_index=True, default='待完善', max_length=20, null=True, verbose_name='作者姓名')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name=' 作者昵称')),
                ('age', models.IntegerField(default=0, verbose_name='作者年龄')),
                ('gender', models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=1, null=True, verbose_name='性别')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '锁定'), ('2', '删除')], default='0', help_text='必须选择一个状态', max_length=5, verbose_name='用户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('author_liked', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author')),
                ('authors_liked', models.ManyToManyField(related_name='author', to='author.author')),
            ],
            options={
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='扩展资料编号')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('visited_count', models.IntegerField(default=0, verbose_name='访问量')),
                ('word_count', models.IntegerField(default=0, verbose_name='文章字数')),
                ('aricle_count', models.IntegerField(default=0, verbose_name='文章数')),
                ('collected_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('liked_count', models.IntegerField(default=0, verbose_name='喜欢数')),
                ('admired_count', models.IntegerField(default=0, verbose_name='点赞总数')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
