# Generated by Django 4.2.16 on 2024-11-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authors_liked',
        ),
    ]
